language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
  yarn: true
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
after_success:
- yarn run build --prod
deploy:
  provider: s3
  access_key_id: AKIAJEU4IY3RF52QMP7A
  secret_access_key:
    secure: GQB5VpHfj4Wu32HzYYv3IqYCT8BMzq756q6eDZ6KgHGDQDBJiIXko07yJa/qoLZETCgyF9bSIHO2omMqUJSRFpuMTbtuomQZHhAwoZ36JBdfO5wDrpcmtYSWtjg+m/1oqpyMmfEr+vGPnI1WjBYRujtpJEcf4SpRU9x+W+acx0Sd32ZPqCcTTbLKRaxCRm9CgBXupE2hzUEsQrtvVy6LNK5aysWUyFjytYJ83xRuZuH7pkrKs978T3fcaQFlzt8qJ090/ZptQ4+3TIeS2doK4XKQOESo4VIvQ764X8oaSAs7T5BsZWgum8LO0AQbwFmH4Zd8IEJtlIBaQ58PyDfgoQnkyXdIjoOZ0hMBZvY7byQ3lF0ZB3gS2ZKkFtSMYzLFWDm0WxsFn5TnCvBW3O4SRK6IbzKkJExeGuFzik9H/9tcC+31Y7Di+ZJkaVwrGDV20n6XQwfOLf+Qio2jkTUUCEJGfV1BJWO6LHzV6P7jTgJzt2W1eMSY/Tmn1RRwfzdTHpp+H7RZPVLGQYO3dTJ+i4HiLfFhXn9plQbffWvMpC3eDFYP9pFH5kzNxvaRPH3KeFdTdls68odSJVV8+QcKymJ2+BrFTKj4nXLBAgYlMQ+EsmcBGv3rmfgCSKvLX4lBPLvqH5JlTUcxPPcWYVBVZxHNK2CIOuLUhj92+ZRvdy0=
  bucket: la.iris.bucket
  on:
    branch: travis_karma
  region: us-east-2
  skip_cleanup: true
  local_dir: dist
notifications:
  slack:
    secure: GmMZbJ/pqpfp5r13NoueotUboQdQHu21Zxov916EMa+DDmU/aXllbmdkyB/257OVXOk/w9DMZEg7h3ry+ef6roWd+DgHWOOsZJb9T9m69TcEX5y2a/beShaKjJb88L173u72HwKV+8DszalwxASZN0hJdmIe+8IL3catVf23WMUSUwHMbegJ5fmMKRWJv1tO6Gtw512IWsl5E9HkxRs5fLB+wcKdBIiG1fT4I4VcuII5hMEg5IA1iHc0Gm+jhRuACmTiNDa56lYk/Nby8DLiDZ+PnlxK/hMUFz7VBi+y1NWWMhOJhePu654G+2PCE+erEv+3HThLgNWseDGdGcW5ntGco2AcL1NhK5QxJDUB26DnHUxZCTqjdzu8vdgdB1FLrQbmb+bAccYeKbGShiTw3rzbi3rcVGsQqy+H3WlQjp4PCPR4lK/j5yHuohityFi5FyAjEk2YBx7S/7+MEzaJs0sHPGrKl6Pr80yvKucXF/NxQnV+GVut5wxATuYNUMBwSOS0W3s04+EHjXJZVfVseQBP3nWBgWntL1TCi/lBXBmkXeAzV06kNfnMCY+1n0zPRnEwvbp8ECcKtmYrhm7tHyOiV+wtxq3ze5nQwQ+0jlWX/i8uGwS0cIcbvBKJ4WC/0yVoHJXIgDVFExuUNMZAVn6EH/2wFtHQhuftpB0HmsQ=
